### ISSUE TITLE
Trash Leak

### ISSUE THREAD

**Issue by skidseal** [Cleckzy1337/Fortnite-External-CatWare-Self-leak#1]
This is useless and makes me think what y'all use for catware, this is a average github paste with messy code and detected, uses findwindow and injdrv.

**Comment by Cleckzy1337** [comment]
Ur mad it got leaked L

**Comment by skidseal** [comment]
bro responded in 1 second, you're calling me monkey but begged me not to share

**Comment by skidseal** [comment]
My fault abdul is a retard and got logged, I'll leak the real catware lite if u want to. Hush

**Comment by skidseal** [comment]
I'm the one who brought this in the public, and I have enough proof to end catware..

**Comment by skidseal** [comment]
![image](https://user-images.githubusercontent.com/77218162/158867847-13bd3149-1eda-433b-ba97-6b403d195c76.png)

**Comment by Cleckzy1337** [comment]
Omg no don’t end CatWare I’m so afraid 😭

**Comment by skidseal** [comment]
💀

**Comment by Cleckzy1337** [comment]
💀

**Comment by skidseal** [comment]
![image](https://user-images.githubusercontent.com/77218162/158868126-5f8a5705-b2f8-44ee-9f0e-8be7d899ce83.png)

**Comment by skidseal** [comment]
👁️  still denying it was not your src?

**Comment by skidseal** [comment]
Alright, for sure then.
